kind: ConfigMap
apiVersion: v1
metadata:
  name: aggregator-fluentd-config
data:
  #
  # You can put multiple files if needed. Fluentd will read all of them
  # Config file name must be *.conf.
  #
  app.conf: |-
    <source>
      @type forward
      port 24224
    </source>

    <match **>
      @type copy
      <store>
        @type stdout
      </store>
      <store>
        @type kafka2
        brokers kafka-headless:9092
        use_event_time true

        <buffer topic,tag>
          @type file
          path ./kafka-buffer
          flush_interval 1s
        </buffer>

        <format>
          @type json
        </format>

        topic_key logger
        default_topic logger
      </store>
      <store>
        @type elasticsearch
        host "#{ENV['ELASTIC_HOST']}"
        port 9200
        index_name ${tag}.%Y%m%d%H
        logstash_format true
        include_timestamp true

        <buffer tag,time>
          @type file
          path ./buffer
          timekey 1h
          timekey_wait 5m
          timekey_use_utc true
          flush_mode interval
          flush_interval 30s
        </buffer>
      </store>
      <store>
        @type gcs
        project "#{ENV['GCP_PROJECT']}"
        bucket "#{ENV['GCS_BUCKET']}"
        path ${tag}/%Y/%m/%d/%H/%M
        object_key_format %{path}/%{index}.%{file_extension}
        store_as json

        <buffer tag,time>
          @type file
          path ./gcs-buffer
          timekey 1m
          timekey_wait 10s
          timekey_use_utc true
          flush_mode lazy
        </buffer>
        <format>
          @type json
        </format>
      </store>
    </match>
